import fs from 'fs';
import path from 'path';

const DB_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DB_DIR, 'staywise_db.json');

// Read current mockData.ts or existing DB
console.log('Reading current DB file...');
let currentDb = {};
if (fs.existsSync(DB_FILE)) {
  currentDb = JSON.parse(fs.readFileSync(DB_FILE, 'utf-8'));
}

// Write the rich updated dataset
const updatedDb = {
  version: 2,
  lastUpdated: new Date().toISOString(),
  users: currentDb.users || [],
  properties: [
    {
      id: 'prop-beach-road',
      name: 'Beach Road Apartments',
      type: 'Apartment',
      portfolio: 'Kozhikode Coastal',
      address: 'Beach Road, Near Old Light House',
      city: 'Kozhikode',
      state: 'Kerala',
      pincode: '673032',
      totalUnits: 12,
      occupiedUnits: 11,
      expectedMonthlyRent: 480000,
      collectedRent: 430000,
      pendingRent: 50000,
      imageUrl: '/images/properties/beach-road.jpg',
      status: 'ACTIVE',
      healthScore: 92,
      verificationStatus: 'APPROVED',
      submittedDocs: ['Title_Deed_Kozhikode_Reg.pdf', 'Fire_Safety_NOC_2026.pdf', 'Bescom_Tariff_Card.pdf'],
      amenities: ['Sea View', 'Covered Parking', 'Elevator', '24/7 Security', 'Generator Backup', 'Rooftop Infinity Deck'],
      units: [
        { id: 'unit-101', propertyId: 'prop-beach-road', unitNumber: '101', floor: 1, type: '2 BHK', rentAmount: 25000, depositAmount: 75000, status: 'OCCUPIED', currentTenantId: 't-1', currentTenantName: 'Rahul Menon', leaseEnd: '2027-03-31', areaSqFt: 1250, bedrooms: 2, bathrooms: 2 },
        { id: 'unit-102', propertyId: 'prop-beach-road', unitNumber: '102', floor: 1, type: '2 BHK', rentAmount: 25000, depositAmount: 75000, status: 'OCCUPIED', currentTenantId: 't-2', currentTenantName: 'Ananya Pillai', leaseEnd: '2027-06-30', areaSqFt: 1250, bedrooms: 2, bathrooms: 2 },
        { id: 'unit-201', propertyId: 'prop-beach-road', unitNumber: '201', floor: 2, type: '3 BHK Sea View', rentAmount: 38000, depositAmount: 114000, status: 'OCCUPIED', currentTenantId: 't-3', currentTenantName: 'Dr. Faisal Ahmed', leaseEnd: '2026-12-31', areaSqFt: 1800, bedrooms: 3, bathrooms: 3 },
        { id: 'unit-302', propertyId: 'prop-beach-road', unitNumber: '302', floor: 3, type: '2 BHK Luxury', rentAmount: 25000, depositAmount: 75000, status: 'OCCUPIED', currentTenantId: 't-shyam', currentTenantName: 'Shyam Sundar', leaseEnd: '2027-12-31', areaSqFt: 1350, bedrooms: 2, bathrooms: 2 },
        { id: 'unit-304', propertyId: 'prop-beach-road', unitNumber: '304', floor: 3, type: '2 BHK Sea View', rentAmount: 26000, depositAmount: 78000, status: 'VACANT', areaSqFt: 1300, bedrooms: 2, bathrooms: 2 }
      ]
    },
    {
      id: 'prop-hillview-heights',
      name: 'Hillview Heights Residency',
      type: 'Apartment',
      portfolio: 'Trivandrum Heights',
      address: 'Cliff View Road, Kowdiar',
      city: 'Thiruvananthapuram',
      state: 'Kerala',
      pincode: '695003',
      totalUnits: 6,
      occupiedUnits: 0,
      expectedMonthlyRent: 180000,
      collectedRent: 0,
      pendingRent: 0,
      imageUrl: '/images/properties/beach-road.jpg',
      status: 'VACANT',
      healthScore: 89,
      verificationStatus: 'PENDING',
      submittedDocs: ['Title_Deed_Kowdiar_2026.pdf', 'Panchayat_Occupancy_Cert.pdf', 'Fire_Safety_Clearance.pdf'],
      amenities: ['Clubhouse', 'Solar Grid', '24/7 Security'],
      units: [
        { id: 'unit-h1', propertyId: 'prop-hillview-heights', unitNumber: '101', floor: 1, type: '2 BHK', rentAmount: 30000, depositAmount: 90000, status: 'VACANT', areaSqFt: 1200, bedrooms: 2, bathrooms: 2 }
      ]
    },
    {
      id: 'prop-wayanad-villa',
      name: 'Serene Mist Estate Villa',
      type: 'Estate',
      portfolio: 'Wayanad Hill Retreats',
      address: 'Vythiri Estate Road, Tea Valley',
      city: 'Wayanad',
      state: 'Kerala',
      pincode: '673576',
      totalUnits: 1,
      occupiedUnits: 1,
      expectedMonthlyRent: 150000,
      collectedRent: 150000,
      pendingRent: 0,
      imageUrl: '/images/properties/estate-villa.jpg',
      status: 'ACTIVE',
      healthScore: 96,
      amenities: ['Private Infinity Pool', 'Solar Grid', 'Organic Plantation', 'Servant Quarters', 'Gated Perimeter', 'High-Speed Starlink'],
      units: [
        { id: 'unit-main-estate', propertyId: 'prop-wayanad-villa', unitNumber: 'Private Estate', floor: 1, type: 'Luxury Villa 5BHK', rentAmount: 150000, depositAmount: 450000, status: 'OCCUPIED', currentTenantId: 't-nri', currentTenantName: 'Vikram & Maya Singhania', leaseEnd: '2028-05-15', areaSqFt: 5400, bedrooms: 5, bathrooms: 6 }
      ]
    },
    {
      id: 'prop-infovision',
      name: 'Infovision Commercial Hub',
      type: 'Commercial',
      portfolio: 'Kochi Commercial',
      address: 'Cyber Park Road, Kakkanad',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682030',
      totalUnits: 8,
      occupiedUnits: 7,
      expectedMonthlyRent: 610000,
      collectedRent: 590000,
      pendingRent: 20000,
      imageUrl: '/images/properties/tech-park.jpg',
      status: 'PARTIALLY_OCCUPIED',
      healthScore: 88,
      amenities: ['Central HVAC', '100% DG Backup', 'CAM Management', 'High-Speed Elevators', 'Visitor Parking', 'BMS Automation'],
      units: [
        { id: 'unit-c101', propertyId: 'prop-infovision', unitNumber: 'Suite 101', floor: 1, type: 'Retail Showroom', rentAmount: 85000, depositAmount: 300000, status: 'OCCUPIED', currentTenantName: 'BlueFin Capital', leaseEnd: '2028-01-31', areaSqFt: 2200, bedrooms: 0, bathrooms: 2 },
        { id: 'unit-c201', propertyId: 'prop-infovision', unitNumber: 'Floor 2 Tech Wing', floor: 2, type: 'IT Office Space', rentAmount: 220000, depositAmount: 800000, status: 'OCCUPIED', currentTenantName: 'AeroSys Technologies', leaseEnd: '2029-08-31', areaSqFt: 4800, bedrooms: 0, bathrooms: 4 },
        { id: 'unit-c304', propertyId: 'prop-infovision', unitNumber: 'Suite 304', floor: 3, type: 'Executive Suite', rentAmount: 45000, depositAmount: 150000, status: 'VACANT', areaSqFt: 1100, bedrooms: 0, bathrooms: 1 }
      ]
    },
    {
      id: 'prop-urban-pg',
      name: 'Staywise Urban PG & Co-living',
      type: 'PG',
      portfolio: 'Bangalore Student & Tech Hub',
      address: 'Koramangala 4th Block, 80ft Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
      totalUnits: 120,
      occupiedUnits: 97,
      expectedMonthlyRent: 840000,
      collectedRent: 790000,
      pendingRent: 50000,
      imageUrl: '/images/properties/beach-road.jpg',
      status: 'ACTIVE',
      healthScore: 94,
      amenities: ['High-Speed Wi-Fi', '3x Meals Included', 'Housekeeping', 'Biometric Access', 'Sub-meter Power', 'Rooftop Lounge'],
      units: [
        { id: 'unit-pg-101', propertyId: 'prop-urban-pg', unitNumber: 'Room 101 (2-Sharing)', floor: 1, type: 'Double Sharing AC', rentAmount: 24000, depositAmount: 48000, status: 'OCCUPIED', currentTenantName: 'Aditya & Varun', areaSqFt: 280, bedrooms: 1, bathrooms: 1 },
        { id: 'unit-pg-102', propertyId: 'prop-urban-pg', unitNumber: 'Room 102 (Single)', floor: 1, type: 'Private Suite', rentAmount: 18000, depositAmount: 36000, status: 'OCCUPIED', currentTenantName: 'Karthik Rao', areaSqFt: 180, bedrooms: 1, bathrooms: 1 },
        { id: 'unit-pg-201', propertyId: 'prop-urban-pg', unitNumber: 'Room 201 (4-Sharing)', floor: 2, type: 'Dorm Quad', rentAmount: 32000, depositAmount: 64000, status: 'PARTIALLY_OCCUPIED', currentTenantName: 'Rohan, Dev + 2 Vacant', areaSqFt: 360, bedrooms: 1, bathrooms: 2 }
      ]
    },
    {
      id: 'prop-cochin-logistics',
      name: 'Cochin Port Logistics Park',
      type: 'Warehouse',
      portfolio: 'Kochi Commercial',
      address: 'Vallarpadam Terminal Expressway',
      city: 'Kochi',
      state: 'Kerala',
      pincode: '682504',
      totalUnits: 4,
      occupiedUnits: 3,
      expectedMonthlyRent: 420000,
      collectedRent: 420000,
      pendingRent: 0,
      imageUrl: '/images/properties/tech-park.jpg',
      status: 'ACTIVE',
      healthScore: 91,
      amenities: ['12m Clear Height', '4x Loading Bays', 'Fire Sprinkler NFPA', 'Heavy Truck Parking', '24/7 Security CCTV', 'Weighbridge'],
      units: [
        { id: 'unit-wh-a', propertyId: 'prop-cochin-logistics', unitNumber: 'Bay A (FMCG Storage)', floor: 1, type: 'Grade A Warehouse', rentAmount: 140000, depositAmount: 560000, status: 'OCCUPIED', currentTenantName: 'QuickLogistics India', areaSqFt: 7000, bedrooms: 0, bathrooms: 2 },
        { id: 'unit-wh-b', propertyId: 'prop-cochin-logistics', unitNumber: 'Bay B (Cold Storage Unit)', floor: 1, type: 'Temperature Controlled', rentAmount: 160000, depositAmount: 640000, status: 'OCCUPIED', currentTenantName: 'OceanFresh Seafoods', areaSqFt: 6500, bedrooms: 0, bathrooms: 2 },
        { id: 'unit-wh-c', propertyId: 'prop-cochin-logistics', unitNumber: 'Bay C (Dry Cargo)', floor: 1, type: 'Open Storage Zone', rentAmount: 120000, depositAmount: 480000, status: 'VACANT', areaSqFt: 6000, bedrooms: 0, bathrooms: 1 }
      ]
    },
    {
      id: 'prop-cyber-greens',
      name: 'CyberGreens Smart Residences',
      type: 'Apartment',
      portfolio: 'Hyderabad Tech Corridor',
      address: 'Gachibowli Outer Ring Road, Hitec City Phase 2',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      totalUnits: 18,
      occupiedUnits: 17,
      expectedMonthlyRent: 720000,
      collectedRent: 680000,
      pendingRent: 40000,
      imageUrl: '/images/properties/beach-road.jpg',
      status: 'ACTIVE',
      healthScore: 95,
      verificationStatus: 'APPROVED',
      submittedDocs: ['GHMC_Occupancy_Cert_2025.pdf', 'Fire_Safety_NOC_TS.pdf', 'TSSPDCL_Submeter_Audit.pdf'],
      amenities: ['EV Charging Hub', 'High-Speed Fiber Grid', 'Clubhouse & Badminton Court', '24/7 Gated Security', 'Smart IoT Power Meters', 'Rooftop Solar System'],
      units: [
        { id: 'unit-cg-101', propertyId: 'prop-cyber-greens', unitNumber: '101', floor: 1, type: '3 BHK Luxury', rentAmount: 45000, depositAmount: 135000, status: 'OCCUPIED', currentTenantId: 't-cg-vikram', currentTenantName: 'Vikram Joshi', leaseEnd: '2027-10-31', areaSqFt: 1850, bedrooms: 3, bathrooms: 3 },
        { id: 'unit-cg-102', propertyId: 'prop-cyber-greens', unitNumber: '102', floor: 1, type: '3 BHK Executive', rentAmount: 45000, depositAmount: 135000, status: 'OCCUPIED', currentTenantId: 't-cg-meera', currentTenantName: 'Meera Krishnan', leaseEnd: '2027-08-31', areaSqFt: 1850, bedrooms: 3, bathrooms: 3 },
        { id: 'unit-cg-201', propertyId: 'prop-cyber-greens', unitNumber: '201', floor: 2, type: '2 BHK Premium', rentAmount: 35000, depositAmount: 105000, status: 'OCCUPIED', currentTenantId: 't-cg-arjun', currentTenantName: 'Arjun Reddy', leaseEnd: '2027-05-31', areaSqFt: 1400, bedrooms: 2, bathrooms: 2 },
        { id: 'unit-cg-202', propertyId: 'prop-cyber-greens', unitNumber: '202', floor: 2, type: '2 BHK Premium', rentAmount: 35000, depositAmount: 105000, status: 'OCCUPIED', currentTenantId: 't-cg-pooja', currentTenantName: 'Pooja Hegde', leaseEnd: '2027-09-30', areaSqFt: 1400, bedrooms: 2, bathrooms: 2 },
        { id: 'unit-cg-301', propertyId: 'prop-cyber-greens', unitNumber: '301', floor: 3, type: '4 BHK Penthouse', rentAmount: 85000, depositAmount: 255000, status: 'VACANT', areaSqFt: 2900, bedrooms: 4, bathrooms: 4 }
      ]
    },
    {
      id: 'prop-marina-palms',
      name: 'Marina Palms Executive Co-Living & PG',
      type: 'PG',
      portfolio: 'Chennai OMR IT Corridor',
      address: 'Rajiv Gandhi Salai, Near Tech Park, Sholinganallur',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600119',
      totalUnits: 64,
      occupiedUnits: 58,
      expectedMonthlyRent: 640000,
      collectedRent: 610000,
      pendingRent: 30000,
      imageUrl: '/images/properties/beach-road.jpg',
      status: 'ACTIVE',
      healthScore: 93,
      verificationStatus: 'APPROVED',
      submittedDocs: ['TANGEDCO_Power_Sanction.pdf', 'Chennai_Corp_Trade_License.pdf'],
      amenities: ['Biometric Smart Access', 'High-Speed Wi-Fi 500Mbps', 'South & North Indian Meals', 'Gym & Gaming Zone', 'Daily Housekeeping', '100% DG Power Backup'],
      units: [
        { id: 'unit-mp-101', propertyId: 'prop-marina-palms', unitNumber: 'Room 101 (Double AC)', floor: 1, type: 'Double Sharing AC', rentAmount: 22000, depositAmount: 44000, status: 'OCCUPIED', currentTenantId: 't-mp-karthik', currentTenantName: 'Karthik Subramanian', areaSqFt: 240, bedrooms: 1, bathrooms: 1 },
        { id: 'unit-mp-102', propertyId: 'prop-marina-palms', unitNumber: 'Room 102 (Single Studio)', floor: 1, type: 'Private Studio AC', rentAmount: 16000, depositAmount: 32000, status: 'OCCUPIED', currentTenantId: 't-mp-divya', currentTenantName: 'Divya Nair', areaSqFt: 180, bedrooms: 1, bathrooms: 1 },
        { id: 'unit-mp-201', propertyId: 'prop-marina-palms', unitNumber: 'Room 201 (Triple Sharing)', floor: 2, type: 'Triple Sharing AC', rentAmount: 27000, depositAmount: 54000, status: 'PARTIALLY_OCCUPIED', currentTenantName: 'Harish, Vivek + 1 Vacant', areaSqFt: 320, bedrooms: 1, bathrooms: 1 }
      ]
    },
    {
      id: 'prop-highland-valley',
      name: 'Highland Valley Heritage Tea Estate',
      type: 'Estate',
      portfolio: 'Munnar Mountain Retreats',
      address: 'Mattupetty Lake Road, Top Station Pass',
      city: 'Munnar',
      state: 'Kerala',
      pincode: '685612',
      totalUnits: 4,
      occupiedUnits: 4,
      expectedMonthlyRent: 380000,
      collectedRent: 380000,
      pendingRent: 0,
      imageUrl: '/images/properties/estate-villa.jpg',
      status: 'ACTIVE',
      healthScore: 97,
      verificationStatus: 'APPROVED',
      submittedDocs: ['Title_Deed_Munnar_1982.pdf', 'Forest_Clearance_NOC.pdf', 'KSEB_Hydro_Grid_Sync.pdf'],
      amenities: ['Private Tea Plantation Walk', 'Micro Hydro-Turbine Grid', 'Heated Infinity Plunge Pool', 'Fireplace Living Suites', 'Private Butler & Estate Chef', 'Helipad Access'],
      units: [
        { id: 'unit-hv-cottage1', propertyId: 'prop-highland-valley', unitNumber: 'Presidential Tea Villa', floor: 1, type: 'Luxury Bungalow 4BHK', rentAmount: 180000, depositAmount: 540000, status: 'OCCUPIED', currentTenantId: 't-hv-rajesh', currentTenantName: 'Rajesh & Sunita Venkatesh', leaseEnd: '2028-09-30', areaSqFt: 4200, bedrooms: 4, bathrooms: 5 },
        { id: 'unit-hv-cottage2', propertyId: 'prop-highland-valley', unitNumber: 'Colonial Planter Suite', floor: 1, type: 'Heritage Suite 3BHK', rentAmount: 120000, depositAmount: 360000, status: 'OCCUPIED', currentTenantName: 'David & Sarah Jenkins', leaseEnd: '2027-11-30', areaSqFt: 2800, bedrooms: 3, bathrooms: 3 },
        { id: 'unit-hv-cottage3', propertyId: 'prop-highland-valley', unitNumber: 'Mist Valley Cottage', floor: 1, type: 'Boutique Cottage 2BHK', rentAmount: 80000, depositAmount: 240000, status: 'OCCUPIED', currentTenantName: 'Dr. Anand Kurien', leaseEnd: '2027-06-30', areaSqFt: 1600, bedrooms: 2, bathrooms: 2 }
      ]
    },
    {
      id: 'prop-horizon-tower',
      name: 'Horizon FinTech Commercial Tower',
      type: 'Commercial',
      portfolio: 'Mumbai Financial District',
      address: 'G-Block, Bandra Kurla Complex (BKC)',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400051',
      totalUnits: 6,
      occupiedUnits: 5,
      expectedMonthlyRent: 1250000,
      collectedRent: 1250000,
      pendingRent: 0,
      imageUrl: '/images/properties/tech-park.jpg',
      status: 'ACTIVE',
      healthScore: 96,
      verificationStatus: 'APPROVED',
      submittedDocs: ['MMRDA_Lease_Deed_BKC.pdf', 'Fire_NOC_Mumbai_2026.pdf', 'LEED_Platinum_Certificate.pdf'],
      amenities: ['LEED Platinum Certified', 'Tier-3 Data Center Ready', 'High-Speed Destination Lifts', 'Central HVAC Chiller', 'Valet & 50 Car Basement', '24/7 Redundant Power (Dual Substation)'],
      units: [
        { id: 'unit-ht-401', propertyId: 'prop-horizon-tower', unitNumber: 'Suite 401 (BFSI Wing)', floor: 4, type: 'Grade A Commercial', rentAmount: 450000, depositAmount: 1800000, status: 'OCCUPIED', currentTenantId: 't-ht-vanguard', currentTenantName: 'Vanguard Wealth Advisors', leaseEnd: '2029-12-31', areaSqFt: 5200, bedrooms: 0, bathrooms: 4 },
        { id: 'unit-ht-501', propertyId: 'prop-horizon-tower', unitNumber: 'Suite 501 (Tech Wing)', floor: 5, type: 'IT/Fintech Office', rentAmount: 550000, depositAmount: 2200000, status: 'OCCUPIED', currentTenantId: 't-ht-paynova', currentTenantName: 'PayNova Systems India', leaseEnd: '2030-03-31', areaSqFt: 6400, bedrooms: 0, bathrooms: 6 },
        { id: 'unit-ht-601', propertyId: 'prop-horizon-tower', unitNumber: 'Suite 601 (Executive)', floor: 6, type: 'Executive Suite', rentAmount: 250000, depositAmount: 1000000, status: 'VACANT', areaSqFt: 2800, bedrooms: 0, bathrooms: 2 }
      ]
    }
  ],
  tenants: [
    {
      id: 't-shyam',
      name: 'Shyam Sundar',
      email: 'shyam.sundar@example.com',
      phone: '+91 98460 21980',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '302',
      monthlyRent: 25000,
      depositPaid: 75000,
      leaseStart: '2024-01-01',
      leaseEnd: '2027-12-31',
      rentDueDate: 5,
      salaryDate: 10,
      autopayActive: true,
      reliabilityScore: 87,
      kycVerified: true,
      rewardsBalance: 1250,
      emergencyContact: 'Lakshmi Sundar (+91 94471 88201)'
    },
    {
      id: 't-1',
      name: 'Rahul Menon',
      email: 'rahul.menon@techcorp.in',
      phone: '+91 98950 33411',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '101',
      monthlyRent: 25000,
      depositPaid: 75000,
      leaseStart: '2024-04-01',
      leaseEnd: '2027-03-31',
      rentDueDate: 5,
      autopayActive: false,
      reliabilityScore: 92,
      kycVerified: true,
      rewardsBalance: 2100,
      emergencyContact: 'Deepak Menon (+91 98470 11992)'
    },
    {
      id: 't-2',
      name: 'Ananya Pillai',
      email: 'ananya.p@designstudio.org',
      phone: '+91 97455 60122',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '102',
      monthlyRent: 25000,
      depositPaid: 75000,
      leaseStart: '2024-07-01',
      leaseEnd: '2027-06-30',
      rentDueDate: 5,
      autopayActive: true,
      reliabilityScore: 96,
      kycVerified: true,
      rewardsBalance: 3400,
      emergencyContact: 'Radha Pillai (+91 94960 55110)'
    },
    {
      id: 't-cg-vikram',
      name: 'Vikram Joshi',
      email: 'vikram.j@cloudcore.io',
      phone: '+91 98490 88214',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '101',
      monthlyRent: 45000,
      depositPaid: 135000,
      leaseStart: '2024-11-01',
      leaseEnd: '2027-10-31',
      rentDueDate: 5,
      salaryDate: 1,
      autopayActive: true,
      reliabilityScore: 99,
      kycVerified: true,
      rewardsBalance: 4800,
      emergencyContact: 'Pooja Joshi (+91 98490 88215)'
    },
    {
      id: 't-cg-meera',
      name: 'Meera Krishnan',
      email: 'meera.krishnan@datasystems.ai',
      phone: '+91 99620 44192',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '102',
      monthlyRent: 45000,
      depositPaid: 135000,
      leaseStart: '2024-09-01',
      leaseEnd: '2027-08-31',
      rentDueDate: 5,
      autopayActive: true,
      reliabilityScore: 98,
      kycVerified: true,
      rewardsBalance: 3900,
      emergencyContact: 'K. Krishnan (+91 99620 44190)'
    },
    {
      id: 't-cg-arjun',
      name: 'Arjun Reddy',
      email: 'arjun.reddy@fintechscale.com',
      phone: '+91 98480 33109',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '201',
      monthlyRent: 35000,
      depositPaid: 105000,
      leaseStart: '2024-06-01',
      leaseEnd: '2027-05-31',
      rentDueDate: 5,
      autopayActive: true,
      reliabilityScore: 95,
      kycVerified: true,
      rewardsBalance: 2700,
      emergencyContact: 'Suma Reddy (+91 98480 33100)'
    },
    {
      id: 't-mp-karthik',
      name: 'Karthik Subramanian',
      email: 'karthik.subramanian@techsolutions.in',
      phone: '+91 98401 77312',
      propertyId: 'prop-marina-palms',
      propertyName: 'Marina Palms Executive Co-Living & PG',
      unitNumber: 'Room 101-A',
      monthlyRent: 11000,
      depositPaid: 22000,
      leaseStart: '2025-01-01',
      leaseEnd: '2026-12-31',
      rentDueDate: 1,
      autopayActive: true,
      reliabilityScore: 94,
      kycVerified: true,
      rewardsBalance: 1500,
      emergencyContact: 'Subramanian V. (+91 98401 77300)'
    },
    {
      id: 't-mp-divya',
      name: 'Divya Nair',
      email: 'divya.nair@omrfinance.org',
      phone: '+91 97909 55182',
      propertyId: 'prop-marina-palms',
      propertyName: 'Marina Palms Executive Co-Living & PG',
      unitNumber: 'Room 102 (Single Studio)',
      monthlyRent: 16000,
      depositPaid: 32000,
      leaseStart: '2024-10-01',
      leaseEnd: '2026-09-30',
      rentDueDate: 1,
      autopayActive: true,
      reliabilityScore: 97,
      kycVerified: true,
      rewardsBalance: 2900,
      emergencyContact: 'Gopal Nair (+91 97909 55180)'
    },
    {
      id: 't-hv-rajesh',
      name: 'Rajesh & Sunita Venkatesh',
      email: 'rajesh.venkatesh@heritageassets.com',
      phone: '+91 94430 11980',
      propertyId: 'prop-highland-valley',
      propertyName: 'Highland Valley Heritage Tea Estate',
      unitNumber: 'Presidential Tea Villa',
      monthlyRent: 180000,
      depositPaid: 540000,
      leaseStart: '2023-10-01',
      leaseEnd: '2028-09-30',
      rentDueDate: 1,
      autopayActive: true,
      reliabilityScore: 100,
      kycVerified: true,
      rewardsBalance: 8500,
      emergencyContact: 'Sunita Venkatesh (+91 94430 11981)'
    },
    {
      id: 't-ht-vanguard',
      name: 'Vanguard Wealth Advisors',
      email: 'leasing@vanguardwealth.in',
      phone: '+91 22 6670 9900',
      propertyId: 'prop-horizon-tower',
      propertyName: 'Horizon FinTech Commercial Tower',
      unitNumber: 'Suite 401 (BFSI Wing)',
      monthlyRent: 450000,
      depositPaid: 1800000,
      leaseStart: '2024-01-01',
      leaseEnd: '2029-12-31',
      rentDueDate: 1,
      autopayActive: true,
      reliabilityScore: 100,
      kycVerified: true,
      rewardsBalance: 12000,
      emergencyContact: 'Head of Facilities (+91 22 6670 9901)'
    },
    {
      id: 't-ht-paynova',
      name: 'PayNova Systems India',
      email: 'ops@paynovapayments.com',
      phone: '+91 22 4490 8820',
      propertyId: 'prop-horizon-tower',
      propertyName: 'Horizon FinTech Commercial Tower',
      unitNumber: 'Suite 501 (Tech Wing)',
      monthlyRent: 550000,
      depositPaid: 2200000,
      leaseStart: '2025-04-01',
      leaseEnd: '2030-03-31',
      rentDueDate: 1,
      autopayActive: true,
      reliabilityScore: 100,
      kycVerified: true,
      rewardsBalance: 15000,
      emergencyContact: 'Admin & Real Estate Lead (+91 22 4490 8822)'
    }
  ],
  invoices: [
    {
      id: 'inv-oct-302',
      invoiceNumber: 'STW-2026-10-302',
      tenantId: 't-shyam',
      tenantName: 'Shyam Sundar',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '302',
      period: 'October 2026',
      baseRent: 25000,
      camCharges: 2500,
      utilityCharges: 1200,
      totalAmount: 28700,
      paidAmount: 0,
      dueDate: '2026-10-05',
      status: 'Due'
    },
    {
      id: 'inv-sep-302',
      invoiceNumber: 'STW-2026-09-302',
      tenantId: 't-shyam',
      tenantName: 'Shyam Sundar',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '302',
      period: 'September 2026',
      baseRent: 25000,
      camCharges: 2500,
      utilityCharges: 1100,
      totalAmount: 28600,
      paidAmount: 28600,
      dueDate: '2026-09-05',
      status: 'Paid',
      paymentMethod: 'UPI',
      paidDate: '2026-09-04',
      transactionId: 'UPI-774920198421'
    },
    {
      id: 'inv-oct-101',
      invoiceNumber: 'STW-2026-10-101',
      tenantId: 't-1',
      tenantName: 'Rahul Menon',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '101',
      period: 'October 2026',
      baseRent: 25000,
      camCharges: 2500,
      lateFee: 500,
      totalAmount: 28000,
      paidAmount: 0,
      dueDate: '2026-09-25',
      status: 'Overdue'
    },
    {
      id: 'inv-oct-102',
      invoiceNumber: 'STW-2026-10-102',
      tenantId: 't-2',
      tenantName: 'Ananya Pillai',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '102',
      period: 'October 2026',
      baseRent: 25000,
      camCharges: 2500,
      totalAmount: 27500,
      paidAmount: 27500,
      dueDate: '2026-10-05',
      status: 'Paid',
      paymentMethod: 'Autopay',
      paidDate: '2026-10-01',
      transactionId: 'ACH-AUTO-889104'
    },
    {
      id: 'inv-oct-cg101',
      invoiceNumber: 'STW-2026-10-CG101',
      tenantId: 't-cg-vikram',
      tenantName: 'Vikram Joshi',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '101',
      period: 'October 2026',
      baseRent: 45000,
      camCharges: 4500,
      utilityCharges: 2100,
      totalAmount: 51600,
      paidAmount: 51600,
      dueDate: '2026-10-05',
      status: 'Paid',
      paymentMethod: 'UPI',
      paidDate: '2026-10-01',
      transactionId: 'UPI-HYD-9982401'
    },
    {
      id: 'inv-oct-cg102',
      invoiceNumber: 'STW-2026-10-CG102',
      tenantId: 't-cg-meera',
      tenantName: 'Meera Krishnan',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '102',
      period: 'October 2026',
      baseRent: 45000,
      camCharges: 4500,
      utilityCharges: 1950,
      totalAmount: 51450,
      paidAmount: 51450,
      dueDate: '2026-10-05',
      status: 'Paid',
      paymentMethod: 'Bank Transfer',
      paidDate: '2026-10-02',
      transactionId: 'NB-HDFC-882194'
    },
    {
      id: 'inv-oct-hv01',
      invoiceNumber: 'STW-2026-10-HV01',
      tenantId: 't-hv-rajesh',
      tenantName: 'Rajesh & Sunita Venkatesh',
      propertyId: 'prop-highland-valley',
      propertyName: 'Highland Valley Heritage Tea Estate',
      unitNumber: 'Presidential Tea Villa',
      period: 'October 2026',
      baseRent: 180000,
      camCharges: 15000,
      totalAmount: 195000,
      paidAmount: 195000,
      dueDate: '2026-10-01',
      status: 'Paid',
      paymentMethod: 'Bank Transfer',
      paidDate: '2026-09-30',
      transactionId: 'NEFT-AXIS-MUNNAR-001'
    },
    {
      id: 'inv-oct-ht401',
      invoiceNumber: 'STW-2026-10-HT401',
      tenantId: 't-ht-vanguard',
      tenantName: 'Vanguard Wealth Advisors',
      propertyId: 'prop-horizon-tower',
      propertyName: 'Horizon FinTech Commercial Tower',
      unitNumber: 'Suite 401 (BFSI Wing)',
      period: 'October 2026',
      baseRent: 450000,
      camCharges: 93600,
      utilityCharges: 35000,
      totalAmount: 578600,
      paidAmount: 578600,
      dueDate: '2026-10-01',
      status: 'Paid',
      paymentMethod: 'Bank Transfer',
      paidDate: '2026-09-29',
      transactionId: 'RTGS-BKC-VANGUARD-881'
    },
    {
      id: 'inv-oct-ht501',
      invoiceNumber: 'STW-2026-10-HT501',
      tenantId: 't-ht-paynova',
      tenantName: 'PayNova Systems India',
      propertyId: 'prop-horizon-tower',
      propertyName: 'Horizon FinTech Commercial Tower',
      unitNumber: 'Suite 501 (Tech Wing)',
      period: 'October 2026',
      baseRent: 550000,
      camCharges: 115200,
      utilityCharges: 42000,
      totalAmount: 707200,
      paidAmount: 707200,
      dueDate: '2026-10-01',
      status: 'Paid',
      paymentMethod: 'Bank Transfer',
      paidDate: '2026-09-30',
      transactionId: 'RTGS-BKC-PAYNOVA-992'
    }
  ],
  ledger: [
    {
      id: 'ledg-001',
      timestamp: '2026-10-01 09:15 AM',
      description: 'Rent Collection - Unit 102 (Ananya Pillai)',
      type: 'CREDIT',
      amount: 27500,
      account: 'Client Escrow / Axis Clearing',
      entityType: 'RENT',
      referenceId: 'STW-2026-10-102',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-002',
      timestamp: '2026-09-29 02:40 PM',
      description: 'Vendor Payout - RapidCool AC Services (Beach Road Unit 201)',
      type: 'DEBIT',
      amount: 2500,
      account: 'Property Maintenance Operating Wallet',
      entityType: 'MAINTENANCE',
      referenceId: 'WO-2026-881',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-003',
      timestamp: '2026-09-28 11:00 AM',
      description: 'Owner Settlement - Wayanad Estate September Net Yield',
      type: 'DEBIT',
      amount: 142000,
      account: 'HDFC Escrow Disbursement',
      entityType: 'SETTLEMENT',
      referenceId: 'SETTLE-WY-09',
      settlementStatus: 'RECONCILED'
    },
    {
      id: 'ledg-004',
      timestamp: '2026-09-25 04:30 PM',
      description: 'Security Deposit Held - Unit 302 Escrow Retention',
      type: 'CREDIT',
      amount: 75000,
      account: 'Statutory Tenant Deposit Trust',
      entityType: 'SECURITY_DEPOSIT',
      referenceId: 'DEP-302-SHYAM',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-005',
      timestamp: '2026-10-01 10:30 AM',
      description: 'Corporate Rent - Horizon Tower Suite 401 (Vanguard Wealth)',
      type: 'CREDIT',
      amount: 578600,
      account: 'Axis Bank BKC Escrow Vault',
      entityType: 'RENT',
      referenceId: 'STW-2026-10-HT401',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-006',
      timestamp: '2026-10-01 11:15 AM',
      description: 'Corporate Rent - Horizon Tower Suite 501 (PayNova Systems)',
      type: 'CREDIT',
      amount: 707200,
      account: 'Axis Bank BKC Escrow Vault',
      entityType: 'RENT',
      referenceId: 'STW-2026-10-HT501',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-007',
      timestamp: '2026-10-01 02:00 PM',
      description: 'CyberGreens Resident Collections - Unit 101 & 102 Inflow',
      type: 'CREDIT',
      amount: 103050,
      account: 'HDFC Hyderabad Operating Account',
      entityType: 'RENT',
      referenceId: 'STW-2026-10-CG-BATCH',
      settlementStatus: 'CLEARED'
    },
    {
      id: 'ledg-008',
      timestamp: '2026-10-02 04:00 PM',
      description: 'Statutory Solar Grid Export Credit (Munnar Hydro & Micro-Turbine)',
      type: 'CREDIT',
      amount: 18500,
      account: 'KSEB Power Adjustment Account',
      entityType: 'SETTLEMENT',
      referenceId: 'KSEB-CR-2026-09',
      settlementStatus: 'RECONCILED'
    }
  ],
  tickets: [
    {
      id: 'tkt-001',
      ticketNumber: 'TKT-8841',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '302',
      tenantName: 'Shyam Sundar',
      category: 'AC',
      title: 'Master Bedroom AC cooling efficiency drop',
      description: 'The Daikin 1.5T inverter AC is blowing room-temperature air. Indoor fan is operational, compressor may need coolant recharge.',
      priority: 'Medium',
      status: 'Scheduled',
      estimatedCost: 1800,
      requiresOwnerApproval: false,
      vendorId: 'v-cool',
      vendorName: 'RapidCool Aircon Services',
      createdAt: '2026-09-29',
      scheduledDate: '2026-10-02 (Tomorrow 3:00 PM)'
    },
    {
      id: 'tkt-002',
      ticketNumber: 'TKT-8842',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '201',
      tenantName: 'Dr. Faisal Ahmed',
      category: 'Plumbing',
      title: 'Main bathroom concealed pipe leakage',
      description: 'Water seepage visible on adjacent bedroom wall. Requires acoustic pipe inspection and tile restoration.',
      priority: 'Emergency',
      status: 'Triaged',
      estimatedCost: 4500,
      requiresOwnerApproval: true,
      ownerApproved: false,
      createdAt: '2026-09-30'
    },
    {
      id: 'tkt-003',
      ticketNumber: 'TKT-8839',
      propertyId: 'prop-beach-road',
      propertyName: 'Beach Road Apartments',
      unitNumber: '101',
      tenantName: 'Rahul Menon',
      category: 'Electrical',
      title: 'Balcony water heater circuit breaker tripping',
      description: 'Replaced burnt 20A MCB and tested insulation resistance. Unit fully restored.',
      priority: 'High',
      status: 'Completed',
      estimatedCost: 1200,
      actualCost: 1150,
      requiresOwnerApproval: false,
      vendorName: 'Apex Spark Electricals',
      createdAt: '2026-09-27',
      completedAt: '2026-09-28',
      beforePhotoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400'
    },
    {
      id: 'tkt-004',
      ticketNumber: 'TKT-9910',
      propertyId: 'prop-cyber-greens',
      propertyName: 'CyberGreens Smart Residences',
      unitNumber: '101',
      tenantName: 'Vikram Joshi',
      category: 'Electrical',
      title: 'Smart IoT Sub-meter Calibration',
      description: 'IoT sub-meter telemetry dropped off zigbee gateway. Recalibrated RS485 bus.',
      priority: 'Medium',
      status: 'Scheduled',
      estimatedCost: 950,
      requiresOwnerApproval: false,
      vendorName: 'VoltSmart Automation',
      createdAt: '2026-10-01',
      scheduledDate: '2026-10-04 (11:00 AM)'
    },
    {
      id: 'tkt-005',
      ticketNumber: 'TKT-9912',
      propertyId: 'prop-horizon-tower',
      propertyName: 'Horizon FinTech Commercial Tower',
      unitNumber: 'Suite 401',
      tenantName: 'Vanguard Wealth Advisors',
      category: 'AC',
      title: 'AHU Secondary Chilled Water Valve Inspection',
      description: 'Quarterly preventative maintenance on Daikin AHU-4 chiller line.',
      priority: 'Low',
      status: 'Completed',
      estimatedCost: 3200,
      actualCost: 3200,
      requiresOwnerApproval: true,
      ownerApproved: true,
      vendorName: 'BlueStar Commercial HVAC',
      createdAt: '2026-09-25',
      completedAt: '2026-09-26'
    },
    {
      id: 'tkt-006',
      ticketNumber: 'TKT-9914',
      propertyId: 'prop-highland-valley',
      propertyName: 'Highland Valley Heritage Tea Estate',
      unitNumber: 'Presidential Tea Villa',
      tenantName: 'Rajesh Venkatesh',
      category: 'Other',
      title: 'Hydroelectric Micro-Turbine Filter Cleaning',
      description: 'De-silted mountain stream intake penstock following heavy monsoon showers.',
      priority: 'Medium',
      status: 'Completed',
      estimatedCost: 1500,
      actualCost: 1500,
      requiresOwnerApproval: false,
      vendorName: 'Munnar Hydro Tech',
      createdAt: '2026-09-28',
      completedAt: '2026-09-29'
    }
  ],
  leads: [
    {
      id: 'lead-1',
      name: 'Kavita Nambiar',
      phone: '+91 94470 99211',
      email: 'kavita.n@hdfcbank.com',
      preferredArea: 'Beach Road / West Hill',
      budgetMin: 24000,
      budgetMax: 28000,
      moveInUrgency: 'Immediate',
      scoreCategory: 'Hot',
      scoreExplanation: 'Budget matches Unit 304 (₹26K), corporate banking employment verified, requested immediate viewing.',
      stage: 'Visit Scheduled',
      propertyInterest: 'Beach Road Apartments — Unit 304',
      source: 'Staywise Direct Listing',
      createdAt: '2026-09-28',
      assignedAgent: 'Arjun Das (Leasing Mgr)',
      visitDate: '2026-10-01 at 05:00 PM'
    },
    {
      id: 'lead-2',
      name: 'Siddharth Varma',
      phone: '+91 98471 22340',
      email: 'sid.varma@startup.co',
      preferredArea: 'Cyber Park / Kakkanad',
      budgetMin: 40000,
      budgetMax: 50000,
      moveInUrgency: 'Within 15 Days',
      scoreCategory: 'Hot',
      scoreExplanation: 'Looking for Infovision Suite 304. GST registered firm, ready with 6 months advance.',
      stage: 'Contacted',
      propertyInterest: 'Infovision Commercial Hub — Suite 304',
      source: 'Website Organic',
      createdAt: '2026-09-29',
      assignedAgent: 'Arjun Das (Leasing Mgr)'
    },
    {
      id: 'lead-3',
      name: 'Gautam Ramachandran',
      phone: '+91 99951 88712',
      email: 'gautam.r@gmail.com',
      preferredArea: 'Beach Road',
      budgetMin: 20000,
      budgetMax: 22000,
      moveInUrgency: 'Next Month',
      scoreCategory: 'Warm',
      scoreExplanation: 'Budget slightly below asking (₹26K), flexible move-in date.',
      stage: 'New',
      propertyInterest: 'Beach Road Apartments',
      source: 'WhatsApp Referral',
      createdAt: '2026-09-30',
      assignedAgent: 'Arjun Das (Leasing Mgr)'
    },
    {
      id: 'lead-4',
      name: 'Tanvi Agarwal (Goldman Sachs)',
      phone: '+91 98200 44910',
      email: 'tanvi.agarwal@gs.com',
      preferredArea: 'BKC / Bandra East',
      budgetMin: 220000,
      budgetMax: 260000,
      moveInUrgency: 'Immediate',
      scoreCategory: 'Hot',
      scoreExplanation: 'Corporate lease request for Horizon Tower Suite 601. Financial security deposit approved.',
      stage: 'Proposal Sent',
      propertyInterest: 'Horizon FinTech Commercial Tower — Suite 601',
      source: 'Staywise Enterprise Broker Channel',
      createdAt: '2026-10-02',
      assignedAgent: 'Arjun Das (Leasing Mgr)',
      visitDate: '2026-10-05 at 03:30 PM'
    },
    {
      id: 'lead-5',
      name: 'Nikhil R. (Microsoft Hyderabad)',
      phone: '+91 98491 55210',
      email: 'nikhil.r@outlook.com',
      preferredArea: 'Hitec City / Gachibowli',
      budgetMin: 80000,
      budgetMax: 90000,
      moveInUrgency: 'Within 15 Days',
      scoreCategory: 'Hot',
      scoreExplanation: 'Seeking CyberGreens 4BHK Penthouse (#301). Immediate family relocation.',
      stage: 'Visit Scheduled',
      propertyInterest: 'CyberGreens Smart Residences — Unit 301',
      source: 'Direct Portal',
      createdAt: '2026-10-02',
      assignedAgent: 'Arjun Das (Leasing Mgr)',
      visitDate: '2026-10-04 at 04:00 PM'
    }
  ],
  estateAssets: currentDb.estateAssets || [],
  staff: currentDb.staff || [],
  utilities: currentDb.utilities || [],
  electricityBills: currentDb.electricityBills || [],
  aiInsights: currentDb.aiInsights || [],
  pgBeds: [
    ...(currentDb.pgBeds || []),
    { id: 'bed-mp-101-a', bedCode: 'MP101-A', roomId: 'room-mp-101', roomNumber: '101', floor: 1, sharingType: '2-Sharing', status: 'Occupied', monthlyRent: 11000, deposit: 22000, tenantId: 't-mp-karthik', tenantName: 'Karthik Subramanian', tenantPhone: '+91 98401 77312', ac: true, attachedBath: true, foodIncluded: true, wifiIncluded: true, laundryIncluded: true },
    { id: 'bed-mp-101-b', bedCode: 'MP101-B', roomId: 'room-mp-101', roomNumber: '101', floor: 1, sharingType: '2-Sharing', status: 'Occupied', monthlyRent: 11000, deposit: 22000, tenantName: 'Dinesh K.', tenantPhone: '+91 98401 77315', ac: true, attachedBath: true, foodIncluded: true, wifiIncluded: true, laundryIncluded: true },
    { id: 'bed-mp-102-a', bedCode: 'MP102-A', roomId: 'room-mp-102', roomNumber: '102', floor: 1, sharingType: 'Single', status: 'Occupied', monthlyRent: 16000, deposit: 32000, tenantId: 't-mp-divya', tenantName: 'Divya Nair', tenantPhone: '+91 97909 55182', ac: true, attachedBath: true, foodIncluded: true, wifiIncluded: true, laundryIncluded: true }
  ],
  pgRooms: currentDb.pgRooms || [],
  pgMeals: currentDb.pgMeals || [],
  commercialUnits: [
    ...(currentDb.commercialUnits || []),
    {
      id: 'comm-ht-401',
      propertyId: 'prop-horizon-tower',
      unitNumber: 'Suite 401 (BFSI Wing)',
      floor: 4,
      businessName: 'Vanguard Wealth Advisors',
      businessType: 'Wealth Management & Private Equity',
      areaSqFt: 5200,
      baseRent: 450000,
      camRatePerSqFt: 18,
      camAmount: 93600,
      parkingSlots: 8,
      lockInPeriodMonths: 60,
      noticePeriodMonths: 6,
      escalationPercent: 5,
      fitOutStatus: 'Ready for Opening',
      status: 'Occupied'
    },
    {
      id: 'comm-ht-501',
      propertyId: 'prop-horizon-tower',
      unitNumber: 'Suite 501 (Tech Wing)',
      floor: 5,
      businessName: 'PayNova Systems India',
      businessType: 'FinTech Payment Infrastructure',
      areaSqFt: 6400,
      baseRent: 550000,
      camRatePerSqFt: 18,
      camAmount: 115200,
      parkingSlots: 12,
      lockInPeriodMonths: 60,
      noticePeriodMonths: 6,
      escalationPercent: 7.5,
      fitOutStatus: 'Ready for Opening',
      status: 'Occupied'
    }
  ],
  camExpenses: currentDb.camExpenses || [],
  commercialVisitors: currentDb.commercialVisitors || [],
  moveFlowChecklist: currentDb.moveFlowChecklist || [],
  depositDisputes: currentDb.depositDisputes || [],
  referrals: currentDb.referrals || [],
  influencerOffers: currentDb.influencerOffers || [],
  subscriptions: currentDb.subscriptions || []
};

// Write updated DB
fs.writeFileSync(DB_FILE, JSON.stringify(updatedDb, null, 2), 'utf-8');
console.log(`Successfully updated ${DB_FILE} with ${updatedDb.properties.length} properties, ${updatedDb.tenants.length} tenants, and ${updatedDb.invoices.length} invoices.`);
